"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path


SECRET_KEY = os.environ.get('SECRET_KEY', '开发环境默认密钥')

  # 项目根目录下的 staticfiles/


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

STATIC_URL = '/static/'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'django_summernote'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# 兼容多种平台的数据库配置（Railway、本地等）
import re

def get_database_config():
    # 1. 优先检查 MYSQL_URL 和 DATABASE_URL（Railway 常用格式）
    database_url = os.environ.get('MYSQL_URL') or os.environ.get('DATABASE_URL')
    if database_url:
        # 支持 mysql:// 和 mysql2:// 格式
        match = re.match(r'mysql2?://([^:]+):([^@]+)@([^:]+):(\d+)/(.+)', database_url)
        if match:
            return {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': match.group(5),
                'USER': match.group(1),
                'PASSWORD': match.group(2),
                'HOST': match.group(3),
                'PORT': match.group(4),
            }
    
    # 2. 兼容 Railway MySQL 服务的环境变量命名（带下划线版本）
    # Railway MySQL 通常设置：MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE, MYSQL_HOST, MYSQL_PORT
    db_user = os.environ.get('MYSQL_USER') or os.environ.get('MYSQLUSER')
    db_password = os.environ.get('MYSQL_PASSWORD') or os.environ.get('MYSQLPASSWORD')
    db_name = os.environ.get('MYSQL_DATABASE') or os.environ.get('MYSQLDATABASE')
    db_host = os.environ.get('MYSQL_HOST') or os.environ.get('MYSQLHOST')
    db_port = os.environ.get('MYSQL_PORT') or os.environ.get('MYSQLPORT')
    
    if db_user and db_password and db_name and db_host:
        return {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port or '3306',
        }
    
    # 3. 兼容其他平台的环境变量命名
    return {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DATABASE_NAME', 'blog'),
        'USER': os.environ.get('DATABASE_USER', 'root'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'root'),
        'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DATABASE_PORT', '3307'),
    }

DATABASES = {
    'default': get_database_config()
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/




# 支持的文件上传大小限制（可选）
SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '480',
    }
}

# 文件路径：blog_project/settings.py 末尾添加
LOGIN_URL = 'login'                    # 未登录用户访问保护页面时跳转到登录页
LOGIN_REDIRECT_URL = 'index'           # 登录成功后跳转到首页
LOGOUT_REDIRECT_URL = 'index'          # 登出后跳转到首页
